### ISSUE TITLE
Um fórum de perguntas e respostas aqui nas issues seria bem legal!

### ISSUE THREAD

**Issue by wilsonneto-dev** [DenoBrasil/deno-forum#2]
Essa é a ideia aqui?

Shoow!! 
E fazer isso para fomentar e para se ajudar, to começando meu primeiro projeto em deno! Já uso demais node + express + TS... Vamos ver qual é a desse carinha chamado deno rs

Abraços!

**Comment by LauraBeatris** [comment]
Faala @wilsonneto-dev 😄 

Estamos planejando em transformar esse repositório em um forum, onde as issues vão centralizar a maior parte das dúvidas relacionados ao Deno por parte da comunidade brasileira.
Isso vai ajudar muito pra quem está começando já que o ecossistema/libs não possuem uma documentação tão detalhada. 

Em breve iremos criar uma plataforma para o forum e também um site da organização onde vamos anunciar eventos. 

Valeu por contribuir <3

**Comment by wilsonneto-dev** [comment]
Massa!! 

Eu uso muitos fóruns por issues e gosto bastante! Acho uma ótima, pode ter certeza que mandarei as dúvidas, assim como também no que puder ajudar alguém irei!

Parabéns pela iniciativa, e muito obrigado tbm :)

**Comment by LauraBeatris** [comment]
Eu que agradeço pela contribuição e disponibilidade pra ajudar a comunidade 🚀🖖🏼
